# Generated by Django 4.2.30 on 2026-09-30 01:33

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        ('inventory', '0003_assetverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_number', models.CharField(db_index=True, editable=False, help_text='Auto-generated unique disposal identifier (e.g. DSP-2026-00001)', max_length=50, unique=True)),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.TextField(help_text='Justification for disposal (e.g. irreparable, obsolete, condemned)')),
                ('condition_at_disposal', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('UNSERVICEABLE', 'Unserviceable')], help_text='Physical condition of the asset at time of disposal request', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, help_text='Approval or rejection notes')),
                ('disposal_method', models.CharField(blank=True, choices=[('SCRAP', 'Scrap / Recycling'), ('DONATION', 'Donation'), ('TRANSFER_OUT', 'Transfer to External Entity'), ('AUCTION', 'Auction / Sale'), ('DESTRUCTION', 'Destruction / Write-off'), ('OTHER', 'Other')], help_text='Method of physical disposal execution', max_length=20)),
                ('disposal_date', models.DateField(blank=True, help_text='Date when physical disposal was executed', null=True)),
                ('recipient_or_destination', models.CharField(blank=True, help_text='Recipient, buyer, or destination of the disposed asset', max_length=300)),
                ('reference_number', models.CharField(blank=True, help_text='Internal document or reference number associated with disposal', max_length=200)),
                ('proceeds_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Informational proceeds from sale/auction in PHP (not official accounting)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when disposal was marked COMPLETED', null=True)),
                ('asset', models.ForeignKey(help_text='The durable asset being disposed', on_delete=django.db.models.deletion.PROTECT, related_name='disposal_records', to='inventory.asset')),
                ('maintenance_reference', models.ForeignKey(blank=True, help_text='Optional maintenance case that recommended this asset for replacement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposal_records', to='maintenance.assetmaintenance')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Administrator who physically executed the disposal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_disposals', to=settings.AUTH_USER_MODEL)),
                ('recommended_by', models.ForeignKey(blank=True, help_text='User who recommended disposal (may differ from requester)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_disposals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='Administrator who initiated the disposal request', on_delete=django.db.models.deletion.PROTECT, related_name='requested_disposals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Administrator who approved or rejected the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_disposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Disposal',
                'verbose_name_plural': 'Asset Disposals',
                'ordering': ['-requested_at', '-id'],
                'indexes': [models.Index(fields=['status', 'asset'], name='disposals_a_status_a027ca_idx'), models.Index(fields=['requested_at'], name='disposals_a_request_b49df4_idx'), models.Index(fields=['disposal_date'], name='disposals_a_disposa_6f7fd7_idx')],
            },
        ),
    ]
