# Generated by Django 4.2.30 on 2026-09-29 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('inventory', '0003_assetverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBorrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('purpose', models.CharField(help_text='Purpose of temporary equipment use.', max_length=500)),
                ('requested_start', models.DateTimeField(db_index=True, help_text='Planned start time of reservation.')),
                ('requested_return', models.DateTimeField(db_index=True, help_text='Expected return deadline.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved (Reserved)'), ('RELEASED', 'Released (Borrowed)'), ('RETURNED', 'Returned'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Required explanation if request is rejected.')),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('condition_at_release', models.CharField(blank=True, choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('UNSERVICEABLE', 'Unserviceable')], help_text='Snapshot of physical condition when equipment left custody.', max_length=20)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('condition_at_return', models.CharField(blank=True, choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('UNSERVICEABLE', 'Unserviceable')], help_text='Inspected physical condition upon return.', max_length=20)),
                ('return_remarks', models.TextField(blank=True, help_text='Inspector notes or damage reports on return.')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or instructions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(help_text='The durable physical asset requested or borrowed.', on_delete=django.db.models.deletion.PROTECT, related_name='borrowings', to='inventory.asset')),
                ('borrower', models.ForeignKey(help_text='The employee/faculty member responsible for temporary custody.', on_delete=django.db.models.deletion.PROTECT, related_name='borrowings', to='organizations.employee')),
                ('borrower_department', models.ForeignKey(help_text="The borrower's department at the time of request.", on_delete=django.db.models.deletion.PROTECT, related_name='borrowings', to='organizations.department')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_borrowings', to=settings.AUTH_USER_MODEL)),
                ('returned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_returned_borrowings', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_borrowings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Borrowing',
                'verbose_name_plural': 'Asset Borrowings',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['asset', 'status'], name='borrowing_a_asset_i_752b9d_idx'), models.Index(fields=['borrower', 'status'], name='borrowing_a_borrowe_55e4d5_idx'), models.Index(fields=['status', 'requested_start', 'requested_return'], name='borrowing_a_status_0ae5fb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='assetborrowing',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['RELEASED', 'OVERDUE'])), fields=('asset',), name='unique_active_released_borrowing'),
        ),
    ]
