# Generated by Django 4.2.30 on 2026-09-29 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_asset_asset_image_asset_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(default=django.utils.timezone.now, help_text='Scheduled or effective physical transfer date')),
                ('reason', models.CharField(help_text='Official justification (e.g. Redistribution, Room Reallocation, Faculty Transfer)', max_length=300)),
                ('remarks', models.TextField(blank=True, help_text='Handling notes, condition on dispatch, carrier, or custody context')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Administrator/Officer who authorized the transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(help_text='Physical asset being transferred', on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='inventory.asset')),
                ('from_department', models.ForeignKey(help_text='Source department at time of transfer request', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='organizations.department')),
                ('from_location', models.ForeignKey(blank=True, help_text='Source physical location at time of transfer request', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='organizations.location')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Custodian/Admin who physically executed and confirmed receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transfers', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, help_text='User who initiated the transfer request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to=settings.AUTH_USER_MODEL)),
                ('to_department', models.ForeignKey(help_text='Target destination department', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='organizations.department')),
                ('to_location', models.ForeignKey(blank=True, help_text='Target physical destination location', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='organizations.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='assettransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED'])), fields=('asset',), name='unique_open_transfer_per_asset'),
        ),
    ]
