from decimal import Decimal
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse
from django.views.generic import View, TemplateView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.utils import timezone
from django.core.paginator import Paginator
from django.db.models import Q

from apps.accounts.models import User
from apps.organizations.models import Department, Location, Employee
from apps.inventory.models import Asset, AssetCategory, Brand, AssetVerification
from apps.assignments.models import AssetAssignment
from apps.transfers.models import AssetTransfer
from apps.borrowing.models import AssetBorrowing
from apps.maintenance.models import AssetMaintenance
from apps.supplies.models import Supply, SupplyTransaction, SupplyCategory
from apps.disposals.models import AssetDisposal
from apps.audit.models import AuditLog

from . import services, exporters


class NonFacultyRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    """
    Restricts reporting access to Admin, Dean, and Department Chair.
    Faculty members have personal accountability portals and cannot access
    administrative reports.
    """
    def test_func(self):
        user = self.request.user
        if not user.is_authenticated:
            return False
        return getattr(user, 'is_admin', False) or getattr(user, 'role', '') in [
            User.Role.ADMIN, User.Role.DEAN, User.Role.DEPT_CHAIR
        ]

    def handle_no_permission(self):
        if self.request.user.is_authenticated and getattr(self.request.user, 'role', '') == User.Role.FACULTY:
            raise PermissionDenied("Faculty members do not have access to administrative reporting.")
        return super().handle_no_permission()


class AdminOnlyRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    """Restricts view exclusively to System Administrators."""
    def test_func(self):
        user = self.request.user
        return user.is_authenticated and getattr(user, 'is_admin', False)

    def handle_no_permission(self):
        raise PermissionDenied("Only System Administrators can access this report.")


def build_active_filters_meta(request, filter_labels):
    """Builds a human-readable dict of active filters for exports and headers."""
    meta = {
        'Generated At': timezone.now().strftime('%Y-%m-%d %H:%M:%S'),
        'Generated By': request.user.get_full_name() or request.user.username,
    }
    active_filters_list = []
    for param, label in filter_labels.items():
        val = request.GET.get(param, '').strip()
        if val:
            active_filters_list.append(f"{label}: {val}")
    
    meta['Active Filters'] = "; ".join(active_filters_list) if active_filters_list else "None (All Records)"
    return meta


# ==============================================================================
# 0. CENTRAL REPORTS DASHBOARD
# ==============================================================================

class ReportsDashboardView(NonFacultyRequiredMixin, TemplateView):
    """
    Central catalog of all available operational, accountability,
    inventory, and supply reports.
    """
    template_name = 'reports/reports_dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        chair_dept = services.get_user_department_scope(user)

        # Quick summary metrics for dashboard cards
        asset_qs = Asset.objects.all()
        if chair_dept:
            asset_qs = asset_qs.filter(department=chair_dept)

        context['total_assets'] = asset_qs.count()
        context['active_assets'] = asset_qs.exclude(status=Asset.Status.DISPOSED).count()
        context['disposed_assets'] = asset_qs.filter(status=Asset.Status.DISPOSED).count()

        # Accountability
        assign_qs = AssetAssignment.objects.filter(status=AssetAssignment.Status.ACTIVE)
        if chair_dept:
            assign_qs = assign_qs.filter(Q(employee__department=chair_dept) | Q(asset__department=chair_dept))
        context['active_assignments'] = assign_qs.count()

        # Transfers
        trans_qs = AssetTransfer.objects.all()
        if chair_dept:
            trans_qs = trans_qs.filter(Q(from_department=chair_dept) | Q(to_department=chair_dept))
        context['total_transfers'] = trans_qs.count()

        # Borrowing
        brw_qs = AssetBorrowing.objects.all()
        if chair_dept:
            brw_qs = brw_qs.filter(Q(borrower__department=chair_dept) | Q(asset__department=chair_dept))
        context['active_loans'] = brw_qs.filter(status__in=[AssetBorrowing.Status.RELEASED, AssetBorrowing.Status.OVERDUE]).count()

        # Maintenance
        mnt_qs = AssetMaintenance.objects.all()
        if chair_dept:
            mnt_qs = mnt_qs.filter(asset__department=chair_dept)
        context['open_maintenance'] = mnt_qs.filter(status__in=[
            AssetMaintenance.Status.REPORTED, AssetMaintenance.Status.ASSESSED, AssetMaintenance.Status.IN_REPAIR
        ]).count()

        # Supplies
        context['low_stock_count'] = len(services.supply_services.get_low_stock_supplies())

        # Disposals
        dsp_qs = AssetDisposal.objects.all()
        if chair_dept:
            dsp_qs = dsp_qs.filter(asset__department=chair_dept)
        context['completed_disposals'] = dsp_qs.filter(status=AssetDisposal.Status.COMPLETED).count()

        context['page_title'] = "Operational Reports Catalog"
        context['is_admin'] = getattr(user, 'is_admin', False)
        context['chair_dept'] = chair_dept
        return context


# ==============================================================================
# 1. ASSET INVENTORY REPORT VIEWS
# ==============================================================================

class AssetInventoryReportView(NonFacultyRequiredMixin, View):
    """
    Comprehensive Asset Inventory Report.
    Supports on-screen pagination, CSV export, openpyxl XLSX export, and print view.
    """
    def get(self, request):
        user = request.user
        filters = request.GET.dict()
        assets_qs, summary = services.get_asset_inventory_report(user, filters)

        export_format = request.GET.get('export', '').lower()
        is_print = request.GET.get('print') == '1'

        filter_labels = {
            'scope': 'Scope', 'department': 'Department ID', 'location': 'Location ID',
            'category': 'Category ID', 'brand': 'Brand ID', 'condition': 'Condition',
            'status': 'Status', 'date_from': 'Acquired From', 'date_to': 'Acquired To', 'q': 'Search'
        }
        meta = build_active_filters_meta(request, filter_labels)

        # 1. CSV Export
        if export_format == 'csv':
            headers, rows, _ = services.format_asset_inventory_rows(assets_qs)
            filename = f"CBA_Asset_Inventory_{timezone.now():%Y%m%d}.csv"
            return exporters.export_to_csv(filename, "Asset Inventory Report", meta, headers, rows)

        # 2. XLSX Export
        if export_format == 'xlsx':
            headers, rows, col_types = services.format_asset_inventory_rows(assets_qs)
            filename = f"CBA_Asset_Inventory_{timezone.now():%Y%m%d}.xlsx"
            return exporters.export_to_xlsx(filename, "Asset Inventory Report", meta, headers, rows, sheet_name="Inventory", column_types=col_types)

        # 3. Print View
        if is_print:
            return render(request, 'reports/report_print.html', {
                'report_title': "Asset Inventory Report",
                'metadata': meta,
                'summary': summary,
                'items': assets_qs[:500],
                'headers': ["Code", "Property #", "Item", "Category", "Department", "Location", "Condition", "Status", "Acquired", "Cost (₱)"],
                'report_type': 'assets',
            })

        # 4. Standard On-Screen View (Paginated)
        paginator = Paginator(assets_qs, 25)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        # Filter dropdown choices
        chair_dept = services.get_user_department_scope(user)
        departments = Department.objects.filter(pk=chair_dept.pk) if chair_dept else Department.objects.filter(is_active=True)
        locations = Location.objects.filter(department=chair_dept, is_active=True) if chair_dept else Location.objects.filter(is_active=True)

        query_params = request.GET.copy()
        if 'page' in query_params:
            query_params.pop('page')

        return render(request, 'reports/asset_inventory_report.html', {
            'page_title': "Asset Inventory Report",
            'assets': page_obj,
            'page_obj': page_obj,
            'summary': summary,
            'departments': departments,
            'locations': locations,
            'categories': AssetCategory.objects.filter(is_active=True),
            'brands': Brand.objects.filter(is_active=True),
            'conditions': Asset.Condition.choices,
            'statuses': Asset.Status.choices,
            'query_string': query_params.urlencode(),
            'active_filters': filters,
            'chair_dept': chair_dept,
        })


class AssetByDepartmentReportView(NonFacultyRequiredMixin, View):
    """Grouped asset breakdown by Department."""
    def get(self, request):
        user = request.user
        data = services.get_asset_by_department_summary(user)
        export_format = request.GET.get('export', '').lower()
        is_print = request.GET.get('print') == '1'

        meta = build_active_filters_meta(request, {})

        if export_format in ['csv', 'xlsx']:
            headers = ["Department", "Total Assets", "Active", "Available", "Assigned", "Borrowed", "Maintenance", "Damaged", "Disposed", "Total Active Value (PHP)"]
            rows = []
            col_types = ["left", "integer", "integer", "integer", "integer", "integer", "integer", "integer", "integer", "currency"]
            for item in data:
                c = item['counts']
                rows.append([
                    item['department'].name, c['total'], c['active'], c['available'],
                    c['assigned'], c['borrowed'], c['maintenance'], c['damaged'],
                    c['disposed'], c['total_value']
                ])
            if export_format == 'csv':
                return exporters.export_to_csv("CBA_Assets_by_Department.csv", "Assets by Department", meta, headers, rows)
            else:
                return exporters.export_to_xlsx("CBA_Assets_by_Department.xlsx", "Assets by Department", meta, headers, rows, sheet_name="By Department", column_types=col_types)

        if is_print:
            return render(request, 'reports/report_print.html', {
                'report_title': "Assets by Department Summary",
                'metadata': meta,
                'data': data,
                'report_type': 'by_department',
            })

        return render(request, 'reports/asset_by_department.html', {
            'page_title': "Assets by Department Summary",
            'data': data,
        })


class AssetByLocationReportView(NonFacultyRequiredMixin, View):
    """Grouped asset breakdown by Location/Room."""
    def get(self, request):
        user = request.user
        dept_id = request.GET.get('department')
        data = services.get_asset_by_location_summary(user, department_id=dept_id)
        export_format = request.GET.get('export', '').lower()
        is_print = request.GET.get('print') == '1'

        meta = build_active_filters_meta(request, {'department': 'Department ID'})

        if export_format in ['csv', 'xlsx']:
            headers = ["Location", "Building & Room", "Department", "Total Assets", "Active", "Available", "Assigned", "Damaged", "Maintenance"]
            col_types = ["left", "left", "left", "integer", "integer", "integer", "integer", "integer", "integer"]
            rows = []
            for item in data:
                c = item['counts']
                loc = item['location']
                rows.append([
                    loc.name, f"{loc.building} {loc.room_number}".strip() or "—",
                    loc.department.name if loc.department else "—",
                    c['total'], c['active'], c['available'], c['assigned'],
                    c['damaged'], c['maintenance']
                ])
            if export_format == 'csv':
                return exporters.export_to_csv("CBA_Assets_by_Location.csv", "Assets by Location", meta, headers, rows)
            else:
                return exporters.export_to_xlsx("CBA_Assets_by_Location.xlsx", "Assets by Location", meta, headers, rows, sheet_name="By Location", column_types=col_types)

        chair_dept = services.get_user_department_scope(user)
        departments = Department.objects.filter(pk=chair_dept.pk) if chair_dept else Department.objects.filter(is_active=True)

        return render(request, 'reports/asset_by_location.html', {
            'page_title': "Assets by Location Summary",
            'data': data,
            'departments': departments,
            'selected_dept': dept_id,
        })


# ==============================================================================
# 2. ACCOUNTABILITY REPORT VIEWS
# ==============================================================================

class AccountabilityReportView(NonFacultyRequiredMixin, View):
    """Current Active Faculty/Staff Accountability Report."""
    def get(self, request):
        user = request.user
        filters = request.GET.dict()
        qs, summary = services.get_accountability_report(user, filters, historical=False)

        export_format = request.GET.get('export', '').lower()
        is_print = request.GET.get('print') == '1'

        meta = build_active_filters_meta(request, {
            'department': 'Department ID', 'employee': 'Employee ID',
            'condition': 'Condition', 'date_from': 'Assigned From', 'date_to': 'Assigned To', 'q': 'Search'
        })

        if export_format == 'csv':
            headers, rows, _ = services.format_accountability_rows(qs, historical=False)
            return exporters.export_to_csv(f"CBA_Accountability_Active_{timezone.now():%Y%m%d}.csv", "Faculty Accountability Report", meta, headers, rows)

        if export_format == 'xlsx':
            headers, rows, col_types = services.format_accountability_rows(qs, historical=False)
            return exporters.export_to_xlsx(f"CBA_Accountability_Active_{timezone.now():%Y%m%d}.xlsx", "Faculty Accountability Report", meta, headers, rows, sheet_name="Accountability", column_types=col_types)

        if is_print:
            return render(request, 'reports/report_print.html', {
                'report_title': "Faculty Accountability Report (Active Assignments)",
                'metadata': meta,
                'summary': summary,
                'items': qs[:500],
                'headers': ["Employee", "Dept", "Asset Code", "Item Name", "Property #", "Location", "Condition", "Assigned Date"],
                'report_type': 'accountability',
            })

        paginator = Paginator(qs, 25)
        page_obj = paginator.get_page(request.GET.get('page'))

        chair_dept = services.get_user_department_scope(user)
        departments = Department.objects.filter(pk=chair_dept.pk) if chair_dept else Department.objects.filter(is_active=True)
        employees = Employee.objects.filter(department=chair_dept, is_active=True) if chair_dept else Employee.objects.filter(is_active=True)

        query_params = request.GET.copy()
        if 'page' in query_params:
            query_params.pop('page')

        return render(request, 'reports/accountability_report.html', {
            'page_title': "Current Faculty Accountability Report",
            'assignments': page_obj,
            'page_obj': page_obj,
            'summary': summary,
            'departments': departments,
            'employees': employees,
            'conditions': Asset.Condition.choices,
            'query_string': query_params.urlencode(),
            'active_filters': filters,
            'is_historical': False,
        })


class AccountabilityHistoryReportView(NonFacultyRequiredMixin, View):
    """Historical Assignment & Turnover Report."""
    def get(self, request):
        user = request.user
        filters = request.GET.dict()
        qs, summary = services.get_accountability_report(user, filters, historical=True)

        export_format = request.GET.get('export', '').lower()
        is_print = request.GET.get('print') == '1'

        meta = build_active_filters_meta(request, {
            'department': 'Department ID', 'employee': 'Employee ID',
            'condition': 'Return Condition', 'date_from': 'Assigned From', 'date_to': 'Assigned To', 'q': 'Search'
        })

        if export_format == 'csv':
            headers, rows, _ = services.format_accountability_rows(qs, historical=True)
            return exporters.export_to_csv(f"CBA_Accountability_History_{timezone.now():%Y%m%d}.csv", "Assignment Turnover History", meta, headers, rows)

        if export_format == 'xlsx':
            headers, rows, col_types = services.format_accountability_rows(qs, historical=True)
            return exporters.export_to_xlsx(f"CBA_Accountability_History_{timezone.now():%Y%m%d}.xlsx", "Assignment Turnover History", meta, headers, rows, sheet_name="Turnover History", column_types=col_types)

        if is_print:
            return render(request, 'reports/report_print.html', {
                'report_title': "Assignment & Turnover History Report",
                'metadata': meta,
                'summary': summary,
                'items': qs[:500],
                'headers': ["Employee", "Dept", "Asset Code", "Item Name", "Assigned", "Returned", "Cond Out", "Cond In"],
                'report_type': 'accountability_history',
            })

        paginator = Paginator(qs, 25)
        page_obj = paginator.get_page(request.GET.get('page'))

        chair_dept = services.get_user_department_scope(user)
        departments = Department.objects.filter(pk=chair_dept.pk) if chair_dept else Department.objects.filter(is_active=True)
        employees = Employee.objects.filter(department=chair_dept, is_active=True) if chair_dept else Employee.objects.filter(is_active=True)

        query_params = request.GET.copy()
        if 'page' in query_params:
            query_params.pop('page')

        return render(request, 'reports/accountability_report.html', {
            'page_title': "Assignment & Turnover History",
            'assignments': page_obj,
            'page_obj': page_obj,
            'summary': summary,
            'departments': departments,
            'employees': employees,
            'conditions': Asset.Condition.choices,
            'query_string': query_params.urlencode(),
            'active_filters': filters,
            'is_historical': True,
        })


class EmployeeAccountabilityReportView(NonFacultyRequiredMixin, View):
    """Individual Employee Accountability Profile Report."""
    def get(self, request, pk):
        user = request.user
        chair_dept = services.get_user_department_scope(user)

        employee = get_object_or_404(Employee.objects.select_related('department', 'location'), pk=pk)

        # Scoping check
        if chair_dept and employee.department != chair_dept:
            raise PermissionDenied("You cannot view accountability for an employee outside your department.")

        active_assignments = employee.assignments.filter(
            status=AssetAssignment.Status.ACTIVE
        ).select_related('asset', 'asset__category', 'asset__current_location', 'assigned_by')

        past_assignments = employee.assignments.filter(
            status=AssetAssignment.Status.RETURNED
        ).select_related('asset', 'asset__category', 'assigned_by', 'returned_by')

        export_format = request.GET.get('export', '').lower()
        if export_format in ['csv', 'xlsx']:
            meta = {
                'Employee': employee.full_name,
                'Employee ID': employee.employee_id,
                'Department': employee.department.name if employee.department else "—",
                'Position': employee.position or "Staff",
                'Active Assignments Count': active_assignments.count(),
                'Generated At': timezone.now().strftime('%Y-%m-%d %H:%M:%S'),
                'Generated By': user.get_full_name() or user.username,
            }
            headers, rows, col_types = services.format_accountability_rows(active_assignments, historical=False)
            filename = f"CBA_Accountability_{employee.employee_id}_{timezone.now():%Y%m%d}"
            if export_format == 'csv':
                return exporters.export_to_csv(f"{filename}.csv", f"Accountability: {employee.full_name}", meta, headers, rows)
            else:
                return exporters.export_to_xlsx(f"{filename}.xlsx", f"Accountability: {employee.full_name}", meta, headers, rows, sheet_name="Accountability", column_types=col_types)

        if request.GET.get('print') == '1':
            return render(request, 'reports/report_print.html', {
                'report_title': f"Employee Accountability: {employee.full_name} ({employee.employee_id})",
                'metadata': {
                    'Department': employee.department.name if employee.department else "—",
                    'Position': employee.position or "Staff",
                    'Active Custody Items': active_assignments.count(),
                },
                'items': active_assignments,
                'headers': ["Asset Code", "Property #", "Item", "Category", "Location", "Condition", "Assigned Date", "Purpose"],
                'report_type': 'employee_accountability',
            })

        return render(request, 'reports/employee_accountability_report.html', {
            'employee': employee,
            'active_assignments': active_assignments,
            'past_assignments': past_assignments,
            'page_title': f"Accountability: {employee.full_name}",
        })


# ==============================================================================
# 3. ASSET TRANSFER REPORT VIEW
# ==============================================================================

class TransferReportView(NonFacultyRequiredMixin, View):
    """Asset relocation, department transfers, and movement history report."""
    def get(self, request):
        user = request.user
        filters = request.GET.dict()
        qs, summary = services.get_transfer_report(user, filters)

        export_format = request.GET.get('export', '').lower()
        is_print = request.GET.get('print') == '1'

        meta = build_active_filters_meta(request, {
            'department': 'Department ID', 'status': 'Status',
            'date_from': 'Date From', 'date_to': 'Date To', 'q': 'Search'
        })

        if export_format == 'csv':
            headers, rows, _ = services.format_transfer_rows(qs)
            return exporters.export_to_csv(f"CBA_Transfers_Report_{timezone.now():%Y%m%d}.csv", "Asset Movement & Transfer Report", meta, headers, rows)

        if export_format == 'xlsx':
            headers, rows, col_types = services.format_transfer_rows(qs)
            return exporters.export_to_xlsx(f"CBA_Transfers_Report_{timezone.now():%Y%m%d}.xlsx", "Asset Movement & Transfer Report", meta, headers, rows, sheet_name="Transfers", column_types=col_types)

        if is_print:
            return render(request, 'reports/report_print.html', {
                'report_title': "Asset Movement & Transfer Report",
                'metadata': meta,
                'summary': summary,
                'items': qs[:500],
                'headers': ["Transfer ID", "Asset Code", "Item", "From Dept", "To Dept", "Transfer Date", "Status", "Requested By"],
                'report_type': 'transfers',
            })

        paginator = Paginator(qs, 25)
        page_obj = paginator.get_page(request.GET.get('page'))

        chair_dept = services.get_user_department_scope(user)
        departments = Department.objects.filter(pk=chair_dept.pk) if chair_dept else Department.objects.filter(is_active=True)

        query_params = request.GET.copy()
        if 'page' in query_params:
            query_params.pop('page')

        return render(request, 'reports/transfer_report.html', {
            'page_title': "Asset Transfers & Movement Report",
            'transfers': page_obj,
            'page_obj': page_obj,
            'summary': summary,
            'departments': departments,
            'statuses': AssetTransfer.Status.choices,
            'query_string': query_params.urlencode(),
            'active_filters': filters,
        })


# ==============================================================================
# 4. BORROWING & LOAN REPORT VIEWS
# ==============================================================================

class BorrowingReportView(NonFacultyRequiredMixin, View):
    """Temporary asset reservation, active loans, and overdue report."""
    def get(self, request):
        user = request.user
        filters = request.GET.dict()
        overdue_only = request.GET.get('overdue') == '1'

        qs, summary = services.get_borrowing_report(user, filters, overdue_only=overdue_only)

        export_format = request.GET.get('export', '').lower()
        is_print = request.GET.get('print') == '1'

        meta = build_active_filters_meta(request, {
            'department': 'Department ID', 'status': 'Status', 'borrower': 'Borrower ID',
            'overdue': 'Overdue Only', 'date_from': 'Date From', 'date_to': 'Date To', 'q': 'Search'
        })

        if export_format == 'csv':
            headers, rows, _ = services.format_borrowing_rows(qs)
            filename = f"CBA_Borrowing_Overdue_{timezone.now():%Y%m%d}.csv" if overdue_only else f"CBA_Borrowing_Report_{timezone.now():%Y%m%d}.csv"
            return exporters.export_to_csv(filename, "Equipment Borrowing Report", meta, headers, rows)

        if export_format == 'xlsx':
            headers, rows, col_types = services.format_borrowing_rows(qs)
            filename = f"CBA_Borrowing_Overdue_{timezone.now():%Y%m%d}.xlsx" if overdue_only else f"CBA_Borrowing_Report_{timezone.now():%Y%m%d}.xlsx"
            return exporters.export_to_xlsx(filename, "Equipment Borrowing Report", meta, headers, rows, sheet_name="Borrowing", column_types=col_types)

        if is_print:
            return render(request, 'reports/report_print.html', {
                'report_title': "Equipment Borrowing & Loan Report",
                'metadata': meta,
                'summary': summary,
                'items': qs[:500],
                'headers': ["Loan ID", "Asset Code", "Item Name", "Borrower", "Start", "Return Deadline", "Status", "Effective State"],
                'report_type': 'borrowing',
            })

        paginator = Paginator(qs, 25)
        page_obj = paginator.get_page(request.GET.get('page'))

        chair_dept = services.get_user_department_scope(user)
        departments = Department.objects.filter(pk=chair_dept.pk) if chair_dept else Department.objects.filter(is_active=True)

        query_params = request.GET.copy()
        if 'page' in query_params:
            query_params.pop('page')

        return render(request, 'reports/borrowing_report.html', {
            'page_title': "Overdue Equipment Loans" if overdue_only else "Equipment Borrowing & Loan Report",
            'borrowings': page_obj,
            'page_obj': page_obj,
            'summary': summary,
            'departments': departments,
            'statuses': AssetBorrowing.Status.choices,
            'overdue_only': overdue_only,
            'query_string': query_params.urlencode(),
            'active_filters': filters,
        })


# ==============================================================================
# 5. MAINTENANCE & REPAIR REPORT VIEWS
# ==============================================================================

class MaintenanceReportView(NonFacultyRequiredMixin, View):
    """Maintenance cases, repair history, and defect reports."""
    def get(self, request):
        user = request.user
        filters = request.GET.dict()
        qs, summary = services.get_maintenance_report(user, filters, replacement_only=False)

        export_format = request.GET.get('export', '').lower()
        is_print = request.GET.get('print') == '1'

        meta = build_active_filters_meta(request, {
            'department': 'Department ID', 'status': 'Status', 'severity': 'Severity',
            'category': 'Category ID', 'service_provider': 'Provider',
            'date_from': 'Reported From', 'date_to': 'Reported To', 'q': 'Search'
        })

        if export_format == 'csv':
            headers, rows, _ = services.format_maintenance_rows(qs)
            return exporters.export_to_csv(f"CBA_Maintenance_Report_{timezone.now():%Y%m%d}.csv", "Equipment Maintenance & Repair Report", meta, headers, rows)

        if export_format == 'xlsx':
            headers, rows, col_types = services.format_maintenance_rows(qs)
            return exporters.export_to_xlsx(f"CBA_Maintenance_Report_{timezone.now():%Y%m%d}.xlsx", "Equipment Maintenance & Repair Report", meta, headers, rows, sheet_name="Maintenance", column_types=col_types)

        if is_print:
            return render(request, 'reports/report_print.html', {
                'report_title': "Equipment Maintenance & Repair Report",
                'metadata': meta,
                'summary': summary,
                'items': qs[:500],
                'headers': ["Case #", "Asset Code", "Item Name", "Issue", "Severity", "Status", "Provider", "Cost (₱)", "Completed"],
                'report_type': 'maintenance',
            })

        paginator = Paginator(qs, 25)
        page_obj = paginator.get_page(request.GET.get('page'))

        chair_dept = services.get_user_department_scope(user)
        departments = Department.objects.filter(pk=chair_dept.pk) if chair_dept else Department.objects.filter(is_active=True)

        query_params = request.GET.copy()
        if 'page' in query_params:
            query_params.pop('page')

        return render(request, 'reports/maintenance_report.html', {
            'page_title': "Equipment Maintenance & Repair Report",
            'cases': page_obj,
            'page_obj': page_obj,
            'summary': summary,
            'departments': departments,
            'categories': AssetCategory.objects.filter(is_active=True),
            'statuses': AssetMaintenance.Status.choices,
            'severities': AssetMaintenance.Severity.choices,
            'query_string': query_params.urlencode(),
            'active_filters': filters,
            'is_replacement': False,
        })


class ReplacementCandidatesReportView(NonFacultyRequiredMixin, View):
    """Assets recommended for replacement or marked as unserviceable."""
    def get(self, request):
        user = request.user
        filters = request.GET.dict()
        qs, summary = services.get_maintenance_report(user, filters, replacement_only=True)

        export_format = request.GET.get('export', '').lower()
        is_print = request.GET.get('print') == '1'

        meta = build_active_filters_meta(request, {
            'department': 'Department ID', 'category': 'Category ID',
            'date_from': 'Reported From', 'date_to': 'Reported To', 'q': 'Search'
        })

        if export_format in ['csv', 'xlsx']:
            headers, rows, col_types = services.format_maintenance_rows(qs)
            filename = f"CBA_Replacement_Candidates_{timezone.now():%Y%m%d}"
            if export_format == 'csv':
                return exporters.export_to_csv(f"{filename}.csv", "Equipment Replacement Recommendations", meta, headers, rows)
            else:
                return exporters.export_to_xlsx(f"{filename}.xlsx", "Equipment Replacement Recommendations", meta, headers, rows, sheet_name="Replacements", column_types=col_types)

        if is_print:
            return render(request, 'reports/report_print.html', {
                'report_title': "Equipment Replacement Recommendations Report",
                'metadata': meta,
                'summary': summary,
                'items': qs[:500],
                'headers': ["Case #", "Asset Code", "Item Name", "Department", "Issue Description", "Condition", "Reported Date"],
                'report_type': 'replacement_candidates',
            })

        paginator = Paginator(qs, 25)
        page_obj = paginator.get_page(request.GET.get('page'))

        chair_dept = services.get_user_department_scope(user)
        departments = Department.objects.filter(pk=chair_dept.pk) if chair_dept else Department.objects.filter(is_active=True)

        query_params = request.GET.copy()
        if 'page' in query_params:
            query_params.pop('page')

        return render(request, 'reports/maintenance_report.html', {
            'page_title': "Replacement Recommendations",
            'cases': page_obj,
            'page_obj': page_obj,
            'summary': summary,
            'departments': departments,
            'categories': AssetCategory.objects.filter(is_active=True),
            'query_string': query_params.urlencode(),
            'active_filters': filters,
            'is_replacement': True,
        })


class MaintenanceCostSummaryReportView(NonFacultyRequiredMixin, View):
    """
    Operational maintenance cost and repair expenditure summary.
    Clearly labelled as recorded operational maintenance expenses.
    """
    def get(self, request):
        user = request.user
        filters = request.GET.dict()
        qs, summary, by_department, top_cases = services.get_maintenance_cost_summary(user, filters)

        export_format = request.GET.get('export', '').lower()
        is_print = request.GET.get('print') == '1'

        meta = build_active_filters_meta(request, {
            'department': 'Department ID', 'date_from': 'Completed From', 'date_to': 'Completed To'
        })

        if export_format in ['csv', 'xlsx']:
            headers = ["Case Number", "Asset Code", "Item Name", "Department", "Service Provider", "Completion Date", "Repair Cost (PHP)"]
            col_types = ["center", "center", "left", "left", "left", "center", "currency"]
            rows = []
            for c in qs:
                rows.append([
                    c.case_number, c.asset.asset_code, c.asset.item_name,
                    c.asset.department.name if c.asset.department else "—",
                    c.service_provider or "—",
                    c.repair_completed_at.strftime('%Y-%m-%d') if c.repair_completed_at else "—",
                    c.repair_cost or Decimal('0.00'),
                ])
            filename = f"CBA_Maintenance_Cost_Summary_{timezone.now():%Y%m%d}"
            if export_format == 'csv':
                return exporters.export_to_csv(f"{filename}.csv", "Maintenance Cost Summary", meta, headers, rows)
            else:
                return exporters.export_to_xlsx(f"{filename}.xlsx", "Maintenance Cost Summary", meta, headers, rows, sheet_name="Cost Summary", column_types=col_types)

        if is_print:
            return render(request, 'reports/report_print.html', {
                'report_title': "Maintenance Cost & Expenditure Summary",
                'metadata': meta,
                'summary': summary,
                'by_department': by_department,
                'items': qs[:500],
                'headers': ["Case #", "Asset Code", "Item Name", "Department", "Provider", "Completed", "Cost (₱)"],
                'report_type': 'cost_summary',
            })

        chair_dept = services.get_user_department_scope(user)
        departments = Department.objects.filter(pk=chair_dept.pk) if chair_dept else Department.objects.filter(is_active=True)

        return render(request, 'reports/maintenance_cost_summary.html', {
            'page_title': "Maintenance Cost Summary",
            'cases': qs[:100],
            'summary': summary,
            'by_department': by_department,
            'top_cases': top_cases,
            'departments': departments,
            'active_filters': filters,
        })


# ==============================================================================
# 6. PHYSICAL INVENTORY VERIFICATION REPORT VIEWS
# ==============================================================================

class VerificationReportView(NonFacultyRequiredMixin, View):
    """Physical inventory verification audit log report."""
    def get(self, request):
        user = request.user
        filters = request.GET.dict()
        mode = request.GET.get('mode', 'all')
        records, summary = services.get_verification_report(user, filters, mode=mode)

        export_format = request.GET.get('export', '').lower()
        is_print = request.GET.get('print') == '1'

        meta = build_active_filters_meta(request, {
            'department': 'Department ID', 'result': 'Result',
            'mode': 'Mode', 'date_from': 'Date From', 'date_to': 'Date To', 'q': 'Search'
        })

        if export_format in ['csv', 'xlsx']:
            headers, rows, col_types = services.format_verification_rows(records, mode=mode)
            filename = f"CBA_Verification_Report_{timezone.now():%Y%m%d}"
            if export_format == 'csv':
                return exporters.export_to_csv(f"{filename}.csv", "Physical Inventory Verification Report", meta, headers, rows)
            else:
                return exporters.export_to_xlsx(f"{filename}.xlsx", "Physical Inventory Verification Report", meta, headers, rows, sheet_name="Verification", column_types=col_types)

        if is_print:
            return render(request, 'reports/report_print.html', {
                'report_title': "Physical Inventory Verification Audit Report",
                'metadata': meta,
                'summary': summary,
                'items': records[:500],
                'headers': ["Asset Code", "Item", "Expected Dept", "Observed Dept", "Expected Loc", "Observed Loc", "Audit Result", "Date"],
                'report_type': 'verification',
            })

        paginator = Paginator(records, 25)
        page_obj = paginator.get_page(request.GET.get('page'))

        chair_dept = services.get_user_department_scope(user)
        departments = Department.objects.filter(pk=chair_dept.pk) if chair_dept else Department.objects.filter(is_active=True)

        query_params = request.GET.copy()
        if 'page' in query_params:
            query_params.pop('page')

        return render(request, 'reports/verification_report.html', {
            'page_title': "Physical Inventory Verification Audits",
            'records': page_obj,
            'page_obj': page_obj,
            'summary': summary,
            'departments': departments,
            'results': AssetVerification.VerificationResult.choices,
            'mode': mode,
            'query_string': query_params.urlencode(),
            'active_filters': filters,
        })


class VerificationMismatchesReportView(NonFacultyRequiredMixin, View):
    """Verification Discrepancies & Mismatches Report."""
    def get(self, request):
        params = request.GET.copy()
        params['mode'] = 'mismatches'
        request.GET = params
        return VerificationReportView.as_view()(request)


class NeverVerifiedReportView(NonFacultyRequiredMixin, View):
    """Assets with no recorded verification history."""
    def get(self, request):
        params = request.GET.copy()
        params['mode'] = 'never_verified'
        request.GET = params
        return VerificationReportView.as_view()(request)


# ==============================================================================
# 7. CONSUMABLE SUPPLIES REPORT VIEWS
# ==============================================================================

class SupplyStockReportView(NonFacultyRequiredMixin, View):
    """
    Authoritative consumable supplies stock report.
    Stock derived strictly from historical transactions.
    """
    def get(self, request):
        user = request.user
        filters = request.GET.dict()
        low_stock_only = request.GET.get('low_stock') == '1'

        supplies, summary = services.get_supply_stock_report(user, filters, low_stock_only=low_stock_only)

        export_format = request.GET.get('export', '').lower()
        is_print = request.GET.get('print') == '1'

        meta = build_active_filters_meta(request, {
            'category': 'Category ID', 'brand': 'Brand ID', 'stock_status': 'Stock Status',
            'low_stock': 'Low Stock Filter', 'q': 'Search'
        })

        if export_format in ['csv', 'xlsx']:
            headers, rows, col_types = services.format_supply_stock_rows(supplies)
            filename = f"CBA_Supply_Stock_{timezone.now():%Y%m%d}"
            if export_format == 'csv':
                return exporters.export_to_csv(f"{filename}.csv", "Consumable Supply Stock Report", meta, headers, rows)
            else:
                return exporters.export_to_xlsx(f"{filename}.xlsx", "Consumable Supply Stock Report", meta, headers, rows, sheet_name="Stock", column_types=col_types)

        if is_print:
            return render(request, 'reports/report_print.html', {
                'report_title': "Consumable Supply Stock Report",
                'metadata': meta,
                'summary': summary,
                'items': supplies,
                'headers': ["Code", "Item Name", "Category", "Unit", "Current Stock", "Reorder Level", "Status", "Shortfall"],
                'report_type': 'supplies',
            })

        paginator = Paginator(supplies, 25)
        page_obj = paginator.get_page(request.GET.get('page'))

        query_params = request.GET.copy()
        if 'page' in query_params:
            query_params.pop('page')

        return render(request, 'reports/supply_stock_report.html', {
            'page_title': "Low-Stock Supplies Alert" if low_stock_only else "Consumable Supply Stock Report",
            'supplies': page_obj,
            'page_obj': page_obj,
            'summary': summary,
            'categories': SupplyCategory.objects.filter(is_active=True),
            'brands': Brand.objects.filter(is_active=True),
            'low_stock_only': low_stock_only,
            'query_string': query_params.urlencode(),
            'active_filters': filters,
        })


class SupplyTransactionsReportView(NonFacultyRequiredMixin, View):
    """Consumable supply ledger transactions report."""
    def get(self, request):
        user = request.user
        filters = request.GET.dict()
        qs, summary = services.get_supply_transactions_report(user, filters)

        export_format = request.GET.get('export', '').lower()
        is_print = request.GET.get('print') == '1'

        meta = build_active_filters_meta(request, {
            'transaction_type': 'Type', 'department': 'Department ID',
            'date_from': 'Date From', 'date_to': 'Date To', 'q': 'Search'
        })

        if export_format in ['csv', 'xlsx']:
            headers, rows, col_types = services.format_supply_transaction_rows(qs)
            filename = f"CBA_Supply_Transactions_{timezone.now():%Y%m%d}"
            if export_format == 'csv':
                return exporters.export_to_csv(f"{filename}.csv", "Supply Ledger Transactions", meta, headers, rows)
            else:
                return exporters.export_to_xlsx(f"{filename}.xlsx", "Supply Ledger Transactions", meta, headers, rows, sheet_name="Transactions", column_types=col_types)

        if is_print:
            return render(request, 'reports/report_print.html', {
                'report_title': "Supply Transactions Audit Log",
                'metadata': meta,
                'summary': summary,
                'items': qs[:500],
                'headers': ["Date", "Supply Code", "Item Name", "Type", "Qty", "Department", "Recipient", "Logged By"],
                'report_type': 'supply_transactions',
            })

        paginator = Paginator(qs, 25)
        page_obj = paginator.get_page(request.GET.get('page'))

        chair_dept = services.get_user_department_scope(user)
        departments = Department.objects.filter(pk=chair_dept.pk) if chair_dept else Department.objects.filter(is_active=True)

        query_params = request.GET.copy()
        if 'page' in query_params:
            query_params.pop('page')

        return render(request, 'reports/supply_transactions_report.html', {
            'page_title': "Supply Transactions Audit Log",
            'transactions': page_obj,
            'page_obj': page_obj,
            'summary': summary,
            'departments': departments,
            'types': SupplyTransaction.TransactionType.choices,
            'query_string': query_params.urlencode(),
            'active_filters': filters,
        })


class SupplyDepartmentUsageReportView(NonFacultyRequiredMixin, View):
    """Consumable supplies issued grouped by department and unit."""
    def get(self, request):
        user = request.user
        filters = request.GET.dict()
        usage_data = services.get_supply_department_usage_report(user, filters)

        export_format = request.GET.get('export', '').lower()
        is_print = request.GET.get('print') == '1'

        meta = build_active_filters_meta(request, {
            'department': 'Department ID', 'date_from': 'Issued From', 'date_to': 'Issued To'
        })

        if export_format in ['csv', 'xlsx']:
            headers = ["Department", "Supply Code", "Item Name", "Unit of Measure", "Total Issued Quantity", "Issuance Transactions"]
            col_types = ["left", "center", "left", "center", "integer", "integer"]
            rows = []
            for u in usage_data:
                rows.append([
                    u['department__name'], u['supply__supply_code'], u['supply__item_name'],
                    u['supply__unit'], u['total_issued'], u['issuance_count']
                ])
            filename = f"CBA_Supply_Department_Usage_{timezone.now():%Y%m%d}"
            if export_format == 'csv':
                return exporters.export_to_csv(f"{filename}.csv", "Supply Usage by Department", meta, headers, rows)
            else:
                return exporters.export_to_xlsx(f"{filename}.xlsx", "Supply Usage by Department", meta, headers, rows, sheet_name="Department Usage", column_types=col_types)

        if is_print:
            return render(request, 'reports/report_print.html', {
                'report_title': "Consumable Supply Usage by Department",
                'metadata': meta,
                'usage_data': usage_data,
                'headers': ["Department", "Supply Code", "Item Name", "Unit", "Total Issued", "Transactions"],
                'report_type': 'supply_usage',
            })

        chair_dept = services.get_user_department_scope(user)
        departments = Department.objects.filter(pk=chair_dept.pk) if chair_dept else Department.objects.filter(is_active=True)

        return render(request, 'reports/supply_department_usage.html', {
            'page_title': "Supply Usage by Department",
            'usage_data': usage_data,
            'departments': departments,
            'active_filters': filters,
        })


# ==============================================================================
# 8. ASSET DISPOSAL REPORT VIEW
# ==============================================================================

class DisposalReportView(NonFacultyRequiredMixin, View):
    """Property disposal, condemnation, and retirement records report."""
    def get(self, request):
        user = request.user
        filters = request.GET.dict()
        qs, summary = services.get_disposal_report(user, filters)

        export_format = request.GET.get('export', '').lower()
        is_print = request.GET.get('print') == '1'

        meta = build_active_filters_meta(request, {
            'department': 'Department ID', 'status': 'Status', 'method': 'Method',
            'date_from': 'Disposed From', 'date_to': 'Disposed To', 'q': 'Search'
        })

        if export_format in ['csv', 'xlsx']:
            headers, rows, col_types = services.format_disposal_rows(qs)
            filename = f"CBA_Disposals_Report_{timezone.now():%Y%m%d}"
            if export_format == 'csv':
                return exporters.export_to_csv(f"{filename}.csv", "Property Disposal & Retirement Report", meta, headers, rows)
            else:
                return exporters.export_to_xlsx(f"{filename}.xlsx", "Property Disposal & Retirement Report", meta, headers, rows, sheet_name="Disposals", column_types=col_types)

        if is_print:
            return render(request, 'reports/report_print.html', {
                'report_title': "Property Disposal & Retirement Report",
                'metadata': meta,
                'summary': summary,
                'items': qs[:500],
                'headers': ["Disposal ID", "Asset Code", "Property #", "Item", "Dept", "Condition", "Status", "Method", "Date", "Proceeds (₱)"],
                'report_type': 'disposals',
            })

        paginator = Paginator(qs, 25)
        page_obj = paginator.get_page(request.GET.get('page'))

        chair_dept = services.get_user_department_scope(user)
        departments = Department.objects.filter(pk=chair_dept.pk) if chair_dept else Department.objects.filter(is_active=True)

        query_params = request.GET.copy()
        if 'page' in query_params:
            query_params.pop('page')

        return render(request, 'reports/disposal_report.html', {
            'page_title': "Property Disposal & Retirement Report",
            'disposals': page_obj,
            'page_obj': page_obj,
            'summary': summary,
            'departments': departments,
            'statuses': AssetDisposal.Status.choices,
            'methods': AssetDisposal.DisposalMethod.choices,
            'query_string': query_params.urlencode(),
            'active_filters': filters,
        })


# ==============================================================================
# 9. SYSTEM AUDIT LOG REPORT VIEW (ADMIN ONLY)
# ==============================================================================

class AuditLogReportView(AdminOnlyRequiredMixin, View):
    """Searchable administrative system audit log report."""
    def get(self, request):
        user = request.user
        filters = request.GET.dict()
        qs, summary = services.get_audit_log_report(user, filters)

        export_format = request.GET.get('export', '').lower()
        is_print = request.GET.get('print') == '1'

        meta = build_active_filters_meta(request, {
            'action': 'Action', 'user': 'User ID',
            'date_from': 'Date From', 'date_to': 'Date To', 'q': 'Search'
        })

        if export_format in ['csv', 'xlsx']:
            headers, rows, col_types = services.format_audit_log_rows(qs)
            filename = f"CBA_Audit_Logs_{timezone.now():%Y%m%d}"
            if export_format == 'csv':
                return exporters.export_to_csv(f"{filename}.csv", "System Audit Log Report", meta, headers, rows)
            else:
                return exporters.export_to_xlsx(f"{filename}.xlsx", "System Audit Log Report", meta, headers, rows, sheet_name="Audit Logs", column_types=col_types)

        if is_print:
            return render(request, 'reports/report_print.html', {
                'report_title': "System Activity & Audit Log Report",
                'metadata': meta,
                'summary': summary,
                'items': qs[:500],
                'headers': ["Timestamp", "User", "Action", "Model Target", "Object ID", "Object Summary", "IP Address"],
                'report_type': 'audit',
            })

        paginator = Paginator(qs, 30)
        page_obj = paginator.get_page(request.GET.get('page'))

        query_params = request.GET.copy()
        if 'page' in query_params:
            query_params.pop('page')

        distinct_actions = AuditLog.objects.values_list('action', flat=True).distinct().order_by('action')
        users = User.objects.filter(is_active=True).order_by('username')

        return render(request, 'reports/audit_log_report.html', {
            'page_title': "System Audit Trail Report",
            'logs': page_obj,
            'page_obj': page_obj,
            'summary': summary,
            'actions': distinct_actions,
            'users': users,
            'query_string': query_params.urlencode(),
            'active_filters': filters,
        })


# ==============================================================================
# 10. EXECUTIVE MULTI-SHEET WORKBOOK EXPORT VIEW
# ==============================================================================

class ExecutiveSummaryXLSXExportView(NonFacultyRequiredMixin, View):
    """
    Downloads the multi-sheet consolidated workbook:
    CBA_Inventory_Executive_Summary_YYYY-MM-DD.xlsx
    Contains: Summary, Assets, Accountability, Borrowing, Maintenance, Supplies, Disposals.
    """
    def get(self, request):
        user = request.user
        sheets_data = services.get_executive_summary_workbook_data(user)
        meta = {
            'Generated At': timezone.now().strftime('%Y-%m-%d %H:%M:%S'),
            'Generated By': user.get_full_name() or user.username,
            'Institutional Scope': 'College-Wide' if getattr(user, 'is_admin', False) or user.role == User.Role.DEAN else f"Department: {user.employee_profile.department.name}",
        }
        filename = f"CBA_Inventory_Executive_Summary_{timezone.now():%Y%m%d}.xlsx"
        return exporters.export_multi_sheet_xlsx(filename, "CBA Inventory Executive Summary", meta, sheets_data)
