# Generated by Django 4.2.30 on 2026-10-08 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0005_asset_is_reservable_assetcategory_is_reservable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, help_text='Institutional Student ID number (e.g. 2023-10482).', max_length=50)),
                ('student_name', models.CharField(help_text='Full name of the student.', max_length=200)),
                ('course_year_section', models.CharField(help_text='Academic course, year, and section (e.g. BSBA 3-A).', max_length=100)),
                ('email', models.EmailField(help_text='Student contact email address.', max_length=254)),
                ('contact_number', models.CharField(help_text='Student contact mobile/telephone number.', max_length=50)),
                ('equipment_type', models.CharField(blank=True, help_text='Requested equipment subtype or specification (e.g. Projector, Speaker, Microphone).', max_length=150)),
                ('requested_pickup', models.DateTimeField(db_index=True, help_text='Scheduled equipment pickup datetime.')),
                ('requested_return', models.DateTimeField(db_index=True, help_text='Scheduled equipment return deadline.')),
                ('purpose', models.CharField(help_text='Official purpose of equipment use (e.g. Class presentation, Student council event).', max_length=500)),
                ('room_venue', models.CharField(blank=True, help_text='Classroom, laboratory, or event venue where equipment will be used.', max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved (Reserved)'), ('RELEASED', 'Released (Active Loan)'), ('RETURNED', 'Returned'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('RETURNED_TO_GUARD', 'Returned to Guard (Awaiting Inspection)')], db_index=True, default='PENDING', max_length=25)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Required explanation if the reservation is rejected.')),
                ('grace_period_minutes', models.PositiveIntegerField(default=15, help_text='Pickup grace period in minutes from requested_pickup (default 15, extendable by Custodian).')),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('condition_at_release', models.CharField(blank=True, choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('UNSERVICEABLE', 'Unserviceable')], help_text='Physical condition snapshot when equipment was handed over to the student.', max_length=20)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('condition_at_return', models.CharField(blank=True, choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('UNSERVICEABLE', 'Unserviceable')], help_text='Physical condition snapshot upon return inspection.', max_length=20)),
                ('return_remarks', models.TextField(blank=True, help_text='Inspection notes or damage details recorded on return.')),
                ('guard_returned_at', models.DateTimeField(blank=True, help_text='Documented handover datetime to security guard after office hours.', null=True)),
                ('guard_handover_details', models.CharField(blank=True, help_text='Documented details of guard handover (e.g. Guard Name, Security Logbook Entry #).', max_length=255)),
                ('guard_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('cba_inspected_at', models.DateTimeField(blank=True, null=True)),
                ('id_deposit_verified', models.BooleanField(default=False, help_text='Indicates whether physical school ID was verified and deposited at CBA office.')),
                ('id_deposited_at', models.DateTimeField(blank=True, null=True)),
                ('id_collected_at', models.DateTimeField(blank=True, help_text='Timestamp when the student physically retrieved their deposited school ID.', null=True)),
                ('id_collection_remarks', models.CharField(blank=True, help_text='Remarks regarding school ID return.', max_length=255)),
                ('lookup_token', models.CharField(db_index=True, editable=False, help_text='Secure, unguessable public lookup token for students to check reservation status.', max_length=64, unique=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional operational remarks.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, help_text='Physical asset allocated by Custodian upon approval.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_reservations', to='inventory.asset')),
                ('category', models.ForeignKey(help_text='Requested equipment category.', on_delete=django.db.models.deletion.PROTECT, related_name='student_reservations', to='inventory.assetcategory')),
                ('cba_inspected_by', models.ForeignKey(blank=True, help_text='CBA Custodian/staff who performed inspection on guard-returned equipment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_student_reservations', to=settings.AUTH_USER_MODEL)),
                ('guard_recorded_by', models.ForeignKey(blank=True, help_text='CBA office staff who entered the guard return into the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guard_recorded_student_reservations', to=settings.AUTH_USER_MODEL)),
                ('id_returned_by', models.ForeignKey(blank=True, help_text='Staff member who returned the deposited school ID to the student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_returned_student_reservations', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_student_reservations', to=settings.AUTH_USER_MODEL)),
                ('returned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_student_reservations', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Reservation',
                'verbose_name_plural': 'Student Reservations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'requested_pickup', 'requested_return'], name='student_res_status_551781_idx'), models.Index(fields=['asset', 'status'], name='student_res_asset_i_433f6a_idx'), models.Index(fields=['lookup_token'], name='student_res_lookup__041bad_idx'), models.Index(fields=['student_id', 'status'], name='student_res_student_80ab06_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['RELEASED', 'RETURNED_TO_GUARD'])), fields=('asset',), name='unique_active_released_student_reservation'),
        ),
    ]
