# Generated by Django 4.2.30 on 2026-09-29 03:10

import apps.inventory.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_image',
            field=models.ImageField(blank=True, help_text='Primary photograph or label image (Max 5MB)', null=True, upload_to='assets/%Y/%m/', validators=[apps.inventory.models.validate_asset_image]),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='acquisition_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Acquisition cost in PHP', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(db_index=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='property_number',
            field=models.CharField(blank=True, help_text='Government/institution property number (e.g. NORSU-CBA-2026-00482)', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('property_number__isnull', False), models.Q(('property_number', ''), _negated=True)), fields=('property_number',), name='unique_non_empty_property_number'),
        ),
    ]
