# Generated by Django 4.2.30 on 2026-09-29 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('inventory', '0002_asset_asset_image_asset_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expected_condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('UNSERVICEABLE', 'Unserviceable')], max_length=20)),
                ('observed_condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('UNSERVICEABLE', 'Unserviceable')], max_length=20)),
                ('result', models.CharField(choices=[('VERIFIED', 'Verified'), ('LOCATION_MISMATCH', 'Location Mismatch'), ('CONDITION_MISMATCH', 'Condition Mismatch'), ('LOCATION_AND_CONDITION_MISMATCH', 'Location and Condition Mismatch')], db_index=True, max_length=40)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='inventory.asset')),
                ('expected_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expected_verifications', to='organizations.department')),
                ('expected_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expected_verifications', to='organizations.location')),
                ('observed_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observed_verifications', to='organizations.department')),
                ('observed_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observed_verifications', to='organizations.location')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducted_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Verification',
                'verbose_name_plural': 'Asset Verifications',
                'ordering': ['-verified_at', '-created_at'],
                'indexes': [models.Index(fields=['asset', '-verified_at'], name='inventory_a_asset_i_32cdea_idx'), models.Index(fields=['result'], name='inventory_a_result_0e474a_idx')],
            },
        ),
    ]
