# Generated by Django 4.2.30 on 2026-09-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_assetverification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='inventory_a_status_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['department', 'status'], name='inventory_a_dept_stat_idx'),
        ),
    ]
