# Generated by Django 4.2.30 on 2026-10-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_reservable',
            field=models.BooleanField(default=True, help_text='Designates whether this specific physical asset can be reserved by students.'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='is_reservable',
            field=models.BooleanField(default=True, help_text='Designates whether equipment in this category can be reserved by students.'),
        ),
    ]
