# Generated by Django 4.2.30 on 2026-09-29 05:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_asset_asset_image_asset_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Unique uppercase category code, e.g. PAPER, WRITE, PRINT, OFFICE, CLEAN', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supply Category',
                'verbose_name_plural': 'Supply Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_code', models.CharField(db_index=True, editable=False, help_text='Auto-generated unique code, e.g. CBA-SUP-PAPER-00001', max_length=50, unique=True)),
                ('item_name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('PIECE', 'Piece'), ('BOX', 'Box'), ('PACK', 'Pack'), ('REAM', 'Ream'), ('BOTTLE', 'Bottle'), ('CARTRIDGE', 'Cartridge'), ('ROLL', 'Roll'), ('SET', 'Set'), ('LITER', 'Liter'), ('KILOGRAM', 'Kilogram')], default='PIECE', max_length=20)),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Threshold quantity that triggers low-stock warning (must be >= 0)', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='inventory.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='supplies.supplycategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_supplies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supply',
                'verbose_name_plural': 'Supplies',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='SupplyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('STOCK_OUT', 'Stock Out'), ('ADJUSTMENT_IN', 'Adjustment In (Count Surplus)'), ('ADJUSTMENT_OUT', 'Adjustment Out (Damage / Loss / Correction)')], db_index=True, max_length=20)),
                ('quantity', models.PositiveIntegerField(help_text='Transaction quantity (must be strictly greater than 0)', validators=[django.core.validators.MinValueValidator(1)])),
                ('reference_number', models.CharField(blank=True, help_text='Delivery receipt, issuance slip, or audit correction reference', max_length=100)),
                ('purpose', models.TextField(blank=True, help_text='Intended use or allocation justification')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or adjustment rationale')),
                ('transaction_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, help_text='Recipient department for stock issuance', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_transactions', to='organizations.department')),
                ('employee', models.ForeignKey(blank=True, help_text='Receiving staff/faculty member', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_issuances', to='organizations.employee')),
                ('location', models.ForeignKey(blank=True, help_text='Destination office/room for stock issuance', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supply_transactions', to='organizations.location')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_supply_transactions', to=settings.AUTH_USER_MODEL)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='supplies.supply')),
            ],
            options={
                'verbose_name': 'Supply Transaction',
                'verbose_name_plural': 'Supply Transactions',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['supply', 'transaction_type', 'transaction_date'], name='supplies_su_supply__ef74e8_idx')],
            },
        ),
    ]
