# Generated by Django 4.2.30 on 2026-09-29 08:04

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_assetverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(db_index=True, editable=False, help_text='Auto-generated unique maintenance identifier (e.g. MNT-2026-00001)', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('ASSESSED', 'Assessed'), ('IN_REPAIR', 'In Repair'), ('COMPLETED', 'Completed'), ('FOR_REPLACEMENT', 'For Replacement'), ('CANCELLED', 'Cancelled')], db_index=True, default='REPORTED', max_length=25)),
                ('severity', models.CharField(blank=True, choices=[('LOW', 'Low - Minor Cosmetic / Non-Essential'), ('MEDIUM', 'Medium - Impaired Functionality'), ('HIGH', 'High - Inoperable / Unusable'), ('CRITICAL', 'Critical - Safety Hazard / Urgent Core Facility')], db_index=True, help_text='Operational severity set during inspection/assessment', max_length=20, null=True)),
                ('source', models.CharField(choices=[('MANUAL_REPORT', 'Manual Report'), ('BORROW_RETURN', 'Borrow Return Inspection'), ('ASSIGNMENT_RETURN', 'Assignment Return Inspection'), ('PHYSICAL_VERIFICATION', 'Physical Inventory Verification'), ('ADMIN_INSPECTION', 'Custodian / Admin Inspection')], default='MANUAL_REPORT', help_text='Operational channel that originated this maintenance incident', max_length=30)),
                ('condition_before', models.CharField(blank=True, choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('UNSERVICEABLE', 'Unserviceable')], help_text='Asset physical condition snapshotted at time of incident/assessment', max_length=20)),
                ('final_condition', models.CharField(blank=True, choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('UNSERVICEABLE', 'Unserviceable')], help_text='Physical condition evaluated upon completion of repair or assessment', max_length=20)),
                ('issue_title', models.CharField(help_text='Short descriptive title of the defect or failure', max_length=200)),
                ('issue_description', models.TextField(help_text='Detailed explanation of observed symptoms, damage, or malfunction')),
                ('reported_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, help_text='Technical finding, root cause, or diagnostic evaluation')),
                ('recommended_action', models.TextField(blank=True, help_text='Proposed corrective action (e.g. in-house servicing, authorized center, part replacement)')),
                ('service_provider', models.CharField(blank=True, help_text='Entity executing repair (e.g., In-house IT, Epson Service Center, Local vendor)', max_length=200)),
                ('technician', models.CharField(blank=True, help_text='Name or contact of servicing technician', max_length=200)),
                ('repair_started_at', models.DateTimeField(blank=True, null=True)),
                ('repair_completed_at', models.DateTimeField(blank=True, null=True)),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Operational repair expense incurred in PHP', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('action_taken', models.TextField(blank=True, help_text='Specific mechanical or electrical repairs performed')),
                ('parts_replaced', models.TextField(blank=True, help_text='Itemized spare parts, modules, or consumables replaced')),
                ('returned_to_service_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_maintenances', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(help_text='The physical asset undergoing maintenance', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='inventory.asset')),
                ('borrowing_reference', models.ForeignKey(blank=True, help_text='Optional borrowing transaction that surfaced the damage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_cases', to='borrowing.assetborrowing')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_maintenances', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(help_text='User who filed the defect report', on_delete=django.db.models.deletion.PROTECT, related_name='reported_maintenances', to=settings.AUTH_USER_MODEL)),
                ('returned_to_service_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_returned_maintenances', to=settings.AUTH_USER_MODEL)),
                ('verification_reference', models.ForeignKey(blank=True, help_text='Optional physical verification audit that flagged a condition mismatch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_cases', to='inventory.assetverification')),
            ],
            options={
                'verbose_name': 'Asset Maintenance',
                'verbose_name_plural': 'Asset Maintenances',
                'ordering': ['-reported_at', '-id'],
                'indexes': [models.Index(fields=['status', 'asset'], name='maintenance_status_bb14e3_idx'), models.Index(fields=['reported_at'], name='maintenance_reporte_032c64_idx')],
            },
        ),
    ]
