# Generated by Django 4.2.30 on 2026-09-29 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_asset_asset_image_asset_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now, help_text='Date accountability took effect')),
                ('expected_return_date', models.DateField(blank=True, help_text='Anticipated return date if temporary', null=True)),
                ('returned_date', models.DateField(blank=True, help_text='Actual date asset was returned and released', null=True)),
                ('purpose', models.CharField(blank=True, help_text='Official purpose (e.g. Instruction, Research, Administrative)', max_length=300)),
                ('condition_at_assignment', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('UNSERVICEABLE', 'Unserviceable')], help_text='Condition snapshot at time of turnover', max_length=20)),
                ('condition_at_return', models.CharField(blank=True, choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('UNSERVICEABLE', 'Unserviceable')], help_text='Condition snapshot upon return', max_length=20, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED', 'Returned')], db_index=True, default='ACTIVE', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Operational notes or accession remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(help_text='Physical asset being assigned', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inventory.asset')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Custodian/Admin who processed assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_assignments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Accountable faculty member or staff', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organizations.employee')),
                ('returned_by', models.ForeignKey(blank=True, help_text='Custodian/Admin who received return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('asset',), name='unique_active_assignment_per_asset'),
        ),
    ]
